### ISSUE TITLE
Dhrystone benchmark issue

### ISSUE THREAD

**Issue by mohamedElbouazzati** [openhwgroup/riscv-ovpsim-corev#1]
I tried to launch the dhrystone benchmark but i get this error :
`Begin Time = 0
End Time   = 0
Measured time too small to obtain meaningful results
Please increase number of runs`

I increased the number of runs in GDB but no results any help please 
thank you

**Comment by Imperas** [comment]
The report is that the dhrystone program as compiled to the .elf does not take long enough to exercise the processor. The provided .elf is just an example to show the simulation runs.

If you want to run longer, change the dhrystone.c NUM_RUNS value and re-compile with your toolchain etc.

Note that running on an instruction accurate simulator does not really provide you with meaningful architectural performance data - you need to run benchmarks like that on the RTL of the device where the micro-architecture affects will be measured... or get a simulator that does timing estimation or performance analysis.

Simon.

**Comment by duncangraham-Imperas** [comment]
The dhrystone.c in this example has the ability to be passed the number of iterations in argv, see line 595: _Number_Of_Runs = (argc >= 2) ? atoi(argv[1]) : NUM_RUNS;_
The arguments can be passed to the applicaiton using the riscvOVPsimCOREV command line by adding, for example _-argv 500000_ (NOTE: This must be the last argument on the comamnd line as all values after the -argv are passed to the applcation in the argument array.

This version of dhrystone.c does NOT read the current time at the start and end of the benchmark execution so the output you are seeing regarding measured time will always be printed due to End_Time = Begin_Time = 0. When you run the benchmark you will see this as:
_Begin Time = 0
End Time   = 0
Measured time too small to obtain meaningful results_

The simulator can allow access to the host time through semihosting (used to show printf output on the host stdout), but this is not being used and probably, as Simon says, has minimal relevance.
